---
abstract: 'Perl OO interface for geojson'
author:
  - 'Michael Jemmeson <mjemmeson@cpan.org>'
build_requires:
  Class::Load: 0
  ExtUtils::MakeMaker: 0
  File::Spec::Functions: 0
  Path::Class: 0
  Test::Fatal: 0
  Test::More: 0
  Test::Most: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-JSON
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Geo::JSON:
    file: lib/Geo/JSON.pm
    version: 0.006
  Geo::JSON::Base:
    file: lib/Geo/JSON/Base.pm
    version: 0.006
  Geo::JSON::CRS:
    file: lib/Geo/JSON/CRS.pm
    version: 0.006
  Geo::JSON::Feature:
    file: lib/Geo/JSON/Feature.pm
    version: 0.006
  Geo::JSON::FeatureCollection:
    file: lib/Geo/JSON/FeatureCollection.pm
    version: 0.006
  Geo::JSON::GeometryCollection:
    file: lib/Geo/JSON/GeometryCollection.pm
    version: 0.006
  Geo::JSON::LineString:
    file: lib/Geo/JSON/LineString.pm
    version: 0.006
  Geo::JSON::MultiLineString:
    file: lib/Geo/JSON/MultiLineString.pm
    version: 0.006
  Geo::JSON::MultiPoint:
    file: lib/Geo/JSON/MultiPoint.pm
    version: 0.006
  Geo::JSON::MultiPolygon:
    file: lib/Geo/JSON/MultiPolygon.pm
    version: 0.006
  Geo::JSON::Point:
    file: lib/Geo/JSON/Point.pm
    version: 0.006
  Geo::JSON::Polygon:
    file: lib/Geo/JSON/Polygon.pm
    version: 0.006
  Geo::JSON::Role::Geometry:
    file: lib/Geo/JSON/Role/Geometry.pm
    version: 0.006
  Geo::JSON::Role::ToJson:
    file: lib/Geo/JSON/Role/ToJson.pm
    version: 0.006
  Geo::JSON::Types:
    file: lib/Geo/JSON/Types.pm
    version: 0.006
  Geo::JSON::Utils:
    file: lib/Geo/JSON/Utils.pm
    version: 0.006
requires:
  Carp: 0
  Exporter: 0
  JSON: 0
  List::Util: 0
  Moo: 0
  Moo::Role: 0
  Type::Library: 0
  Type::Utils: 0
  Types::Standard: 0
  base: 0
  constant: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/mjemmeson/Geo-JSON/issues
  homepage: https://github.com/mjemmeson/Geo-JSON
  repository: https://github.com/mjemmeson/Geo-JSON.git
version: 0.006
x_authority: cpan:DAGOLDEN
